/**
 * Loader for the shared parity fixture (`fixtures/parity_urls.json`).
 *
 * The fixture is generated by the *Python* side (`fixtures/build_parity_fixture.py`)
 * and lives at the repository root. The vitest suite reads it from disk so that
 * the TypeScript implementation is checked against the exact same expected
 * values as the pytest suite. Used only by tests — never bundled into the app.
 */

import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

/** One URL entry in the parity fixture. */
export interface ParityEntry {
  /** The URL string. */
  url: string
  /** A short human note describing the case. */
  note: string
  /** Expected 20-feature record (keys are the fixed feature names). */
  features: Record<string, number>
  /** Expected ML phishing probability (0-1). */
  ml_probability: number
  /** Expected heuristic score (0-100). */
  heuristic_score: number
  /** Expected blended final score (0-100). */
  final_score: number
  /** Expected verdict band. */
  band: string
  /** Expected triggered heuristic rule ids. */
  reason_ids: string[]
}

/** The full parity fixture. */
export interface ParityFixture {
  feature_names: string[]
  model_metrics: Record<string, number>
  count: number
  urls: ParityEntry[]
}

/** Read and parse `fixtures/parity_urls.json` from the repository root. */
export function loadParityFixture(): ParityFixture {
  const here = dirname(fileURLToPath(import.meta.url))
  // here == web/src ; the fixture is two levels up at <repo>/fixtures/.
  const path = resolve(here, '..', '..', 'fixtures', 'parity_urls.json')
  return JSON.parse(readFileSync(path, 'utf-8')) as ParityFixture
}
